name: Build Backend Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false # Set to true if you want to push to DockerHub later
          tags: buzzit-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 51.20.9.183
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # ادخل على مسار المشروع في السيرفر (عدل المسار لو مختلف)
            cd ~/BuzzIt/buzzit-server
            
            # اسحب آخر التحديثات من جيت هاب
            git pull origin master
            
            # ابني الصورة الجديدة
            docker build -t buzzit-backend .
            
            # وقف وامسح الكونتينر القديم لو شغال
            docker stop buzzit-backend-container || true
            docker rm buzzit-backend-container || true
            
            # شغل الكونتينر الجديد في الخلفية
            docker run -d --name buzzit-backend-container -p 4000:4000 --env-file .env buzzit-backend
